# Generated by Django 3.2.5 on 2022-06-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapi', '0002_alter_user_attendance_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_attendance',
            name='checkouttime',
            field=models.TimeField(null=True),
        ),
    ]
