# Generated by Django 3.2.5 on 2022-06-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapi', '0004_auto_20220629_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_attendance',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_attendance',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
