# Generated by Django 3.2.5 on 2022-07-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapi', '0006_alter_leave_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='profile_pics/profile.jpg', upload_to='profile_pics'),
        ),
    ]
