# Generated by Django 3.2.5 on 2022-07-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapi', '0007_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='internship_year',
            field=models.CharField(max_length=4),
        ),
    ]
