# Generated by Django 3.2.5 on 2022-07-02 17:03

import attendanceapi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapi', '0008_alter_profile_internship_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='profile_pics/profile.jpg', upload_to=attendanceapi.models.upload_path),
        ),
    ]
